### ISSUE TITLE
not doing anything.

### ISSUE THREAD

**Issue by flexboj** [DJablonskis/S8nLTU-bot#2]
Hi,
I got it to work as it shows all the panels and stuff but It doesn't do anything and I can't change the toggle from OFF to ON

**Comment by DJablonskis** [comment]
Hi, I was trying to add licenses so it requires login and password at the moment. Just use: 
login: demo@demo.com
password: freedemo

![image](https://user-images.githubusercontent.com/73912470/146903054-67606d56-adc7-4001-a50e-5c3f0d669f02.png)
Then you should see the "Eye" icon and clicking it activates the bot. 

Be aware that "collect rewards" and "watch ads" are at the experimental stage and I would advise against using those.
